
db.url=jdbc:h2:file:./data/usermanager;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
db.username=sa
db.password=


# db.url=jdbc:postgresql://localhost:5432/usermanager
# db.username=postgres
# db.password=YOUR_PASSWORD
